[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings =["@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/","@chainlink/local/=lib/chainlink-local/","@chainlink/contracts=lib/chainlink/contracts/"]
gas_reports = ["*"]
optimizer = true
optimizer_runs = 1000000
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options